name: Unity Activation

on:
  workflow_dispatch:

jobs:
  activation:
    name: Request manual activation template 🔑
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2

      - name: Upload XML license-request file
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v6000.4.8f1.alf
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
